http:
  middlewares:
    security-headers:
      headers:
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        customFrameOptionsValue: "SAMEORIGIN"

  routers:
    treasury:
      rule: Host(`yieldwatch.io`) || Host(`www.yieldwatch.io`)
      service: treasury-api
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      middlewares:
        - security-headers

  services:
    treasury-api:
      loadBalancer:
        servers:
          - url: "http://treasury-api:3000"
